version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Onco_data/:/documents/onco_data/Onco_data
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=KonstaZ
      - POSTGRES_PASSWORD=onco_zugriff@761
      - POSTGRES_DB=Onco_data
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/documents/onco_data/Onco_data/static
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume: