# Generated by Django 2.2.16 on 2020-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_name', models.CharField(max_length=256)),
                ('patients_profile', models.CharField(max_length=256)),
                ('date_condition', models.DateTimeField()),
                ('protocol_date', models.CharField(max_length=128)),
                ('PI', models.PositiveIntegerField(choices=[(1, 'Литвин И.В.'), (2, 'Звонарева Н.Г.')])),
                ('sponsor', models.CharField(max_length=256)),
                ('begin_date', models.DateTimeField()),
                ('monitor', models.CharField(max_length=256)),
                ('first_patient', models.DateTimeField()),
                ('name_doctor_field', models.CharField(max_length=512)),
                ('patients_name_status', models.CharField(max_length=512)),
                ('sae', models.CharField(max_length=512)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('f_o_p_data', models.CharField(max_length=256)),
            ],
        ),
    ]
